import { ArrowUpRight, Globe2, Mail, Menu, Plane, Trophy, X } from 'lucide-react'
import { useState } from 'react'
import { campaignStats, corporateSponsors, socialLinks, teamMembers } from './data/campaignData'
import { formatEur, getCampaignProgress } from './utils/campaignCalculations'
import './App.css'

const progress = getCampaignProgress(campaignStats, corporateSponsors)

const copy = {
  ro: {
    nav: ['Cauza', 'Echipa', 'Proiectul', 'Parteneri'], blondie: 'Despre Blondie', donate: 'Donează',
    date: 'Athens Marathon · 08.11.2026', title: <>Fiecare viață<br /><span>merită o șansă.</span></>, mission: 'Cu fiecare kilometru, să aducem mai multă speranță celor care au cel mai mult nevoie de ea.', donateGalantom: 'Donează prin Galantom', discover: 'Descoperă proiectul', run: <>O alergare.<br />O șansă.</>, progress: 'Progres campanie', individual: 'Donații individuale', sponsors: 'Sponsori', from: 'din',
    impact: ['zboruri medicale', 'copii ajutați', 'costul unui zbor'], causeKicker: '01 / Despre cauză', causeTitle: <>Copiii bolnavi<br /><span>nu au timp.</span></>, causeP1: 'Asociația Blondie oferă transport aerian medical gratuit copiilor români care au nevoie de tratament în afara țării și nu pot călători prin mijloace tradiționale din cauza stării lor de sănătate.', causeP2: 'Nimeni nu merită să audă că „nu se mai poate face nimic”. De aceea, Blondie construiește drumuri către speranță, acolo unde fiecare minut contează.', learn: 'Află mai multe despre Blondie',
    teamKicker: '02 / Echipa Fight for Flights', teamTitle: <>Cinci oameni.<br /><span>O direcție comună.</span></>, teamIntro: 'Masteranzi români din Olanda și Elveția, uniți de o provocare personală pentru o șansă la speranță și viață.',
    projectKicker: '03 / Proiectul', projectTitle: <>Un concept simplu,<br /><span>dar nu ușor.</span></>, projectText: 'O echipă care aleargă maratonul original în scop caritabil. Până la 8 noiembrie 2026, transformăm fiecare kilometru în vizibilitate, implicare și fonduri pentru Blondie.', goal: 'Obiectivul nostru', partnershipKicker: '04 / Parteneriate', partnershipTitle: <>Fă parte din<br /><span>schimbare.</span></>, partnershipText: 'Nu este vorba doar despre donații. Ne dorim campanii care aduc vizibilitate cauzei, promovează sănătatea și sportul și produc un impact real, cuantificabil.', becomePartner: 'Devino partener corporativ', firstPartners: <>Primii noștri parteneri<br /><strong>pot fi aici.</strong></>, discuss: 'Hai să discutăm', footer: 'O inițiativă independentă, aliată cu Asociația Blondie pentru a contribui la strângerea fondurilor necesare zborurilor medicale.', disclaimer: 'Nu suntem parte din Asociația Blondie și nu procesăm donații pe acest site.',
  },
  en: {
    nav: ['Cause', 'Team', 'The project', 'Partners'], blondie: 'About Blondie', donate: 'Donate', date: 'Athens Marathon · 08.11.2026', title: <>Every life<br /><span>deserves a chance.</span></>, mission: 'With every kilometre, let us bring more hope to those who need it most.', donateGalantom: 'Donate through Galantom', discover: 'Discover the project', run: <>One run.<br />One chance.</>, progress: 'Campaign progress', individual: 'Individual donations', sponsors: 'Sponsors', from: 'of', impact: ['medical flights', 'children helped', 'cost of one flight'], causeKicker: '01 / The cause', causeTitle: <>Sick children<br /><span>cannot wait.</span></>, causeP1: 'Asociația Blondie provides free aero-medical transport for Romanian children who need treatment abroad and cannot travel by conventional means because of their health condition.', causeP2: 'No one deserves to hear that “nothing more can be done”. Blondie builds paths to hope, where every minute matters.', learn: 'Learn more about Blondie', teamKicker: '02 / The Fight for Flights team', teamTitle: <>Five people.<br /><span>One shared direction.</span></>, teamIntro: 'Romanian master’s students in the Netherlands and Switzerland, united by a personal challenge for a chance at hope and life.', projectKicker: '03 / The project', projectTitle: <>A simple concept,<br /><span>but not an easy one.</span></>, projectText: 'A team running the original marathon for a charitable cause. Until November 8, 2026, we turn every kilometre into visibility, involvement and funds for Blondie.', goal: 'Our target', partnershipKicker: '04 / Partnerships', partnershipTitle: <>Be part of<br /><span>the change.</span></>, partnershipText: 'This is not only about donations. We want campaigns that bring visibility to the cause, promote health and sport, and create real, measurable impact.', becomePartner: 'Become a corporate partner', firstPartners: <>Our first partners<br /><strong>could be here.</strong></>, discuss: 'Let’s talk', footer: 'An independent initiative allied with Asociația Blondie to help raise the funds needed for aero-medical flights.', disclaimer: 'We are not part of Asociația Blondie and do not process donations on this website.',
  },
  de: {
    nav: ['Ursache', 'Team', 'Projekt', 'Partner'], blondie: 'Über Blondie', donate: 'Spenden', date: 'Athen-Marathon · 08.11.2026', title: <>Jedes Leben<br /><span>verdient eine Chance.</span></>, mission: 'Mit jedem Kilometer bringen wir mehr Hoffnung zu denen, die sie am dringendsten brauchen.', donateGalantom: 'Über Galantom spenden', discover: 'Projekt entdecken', run: <>Ein Lauf.<br />Eine Chance.</>, progress: 'Kampagnenfortschritt', individual: 'Einzelspenden', sponsors: 'Sponsoren', from: 'von', impact: ['medizinische Flüge', 'geholfene Kinder', 'Kosten eines Fluges'], causeKicker: '01 / Die Ursache', causeTitle: <>Kranke Kinder<br /><span>können nicht warten.</span></>, causeP1: 'Asociația Blondie bietet rumänischen Kindern, die im Ausland behandelt werden müssen und aufgrund ihres Gesundheitszustands nicht herkömmlich reisen können, kostenlose medizinische Lufttransporte.', causeP2: 'Niemand verdient es zu hören, dass „nichts mehr getan werden kann“. Blondie baut Wege zur Hoffnung, wo jede Minute zählt.', learn: 'Mehr über Blondie erfahren', teamKicker: '02 / Das Fight for Flights Team', teamTitle: <>Fünf Menschen.<br /><span>Eine gemeinsame Richtung.</span></>, teamIntro: 'Rumänische Masterstudierende in den Niederlanden und der Schweiz, verbunden durch eine persönliche Herausforderung für Hoffnung und Leben.', projectKicker: '03 / Das Projekt', projectTitle: <>Ein einfaches Konzept,<br /><span>aber nicht leicht.</span></>, projectText: 'Ein Team läuft den ursprünglichen Marathon für einen guten Zweck. Bis zum 8. November 2026 verwandeln wir jeden Kilometer in Sichtbarkeit, Engagement und Spenden für Blondie.', goal: 'Unser Ziel', partnershipKicker: '04 / Partnerschaften', partnershipTitle: <>Sei Teil<br /><span>der Veränderung.</span></>, partnershipText: 'Es geht nicht nur um Spenden. Wir möchten Kampagnen entwickeln, die Aufmerksamkeit für die Ursache schaffen, Gesundheit und Sport fördern und messbare Wirkung erzielen.', becomePartner: 'Corporate Partner werden', firstPartners: <>Unsere ersten Partner<br /><strong>könnten hier stehen.</strong></>, discuss: 'Kontakt aufnehmen', footer: 'Eine unabhängige Initiative, die mit Asociația Blondie verbunden ist, um die notwendigen Mittel für medizinische Flüge zu sammeln.', disclaimer: 'Wir sind nicht Teil der Asociația Blondie und verarbeiten keine Spenden auf dieser Website.',
  },
}

const memberCopy = {
  ro: [['Coordonator parteneriate', 'Maratonist la prima cursă'], ['Coordonator fundraising', 'Maratonist la a doua cursă'], ['Coordonator creativ', 'Maratonist la prima cursă'], ['Coordonator evenimente și vizibilitate', 'Maratonist la a doua cursă'], ['Coordonator influenceri și PR', 'Maratonist la prima cursă']],
  en: [['Partnership coordinator', 'First-time marathoner'], ['Fundraising coordinator', 'Second-time marathoner'], ['Creative coordinator', 'First-time marathoner'], ['Event and visibility coordinator', 'Second-time marathoner'], ['Influencer and PR coordinator', 'First-time marathoner']],
  de: [['Koordinator Partnerschaften', 'Erster Marathon'], ['Koordinator Fundraising', 'Zweiter Marathon'], ['Kreativkoordinator', 'Erster Marathon'], ['Koordinator Events und Sichtbarkeit', 'Zweiter Marathon'], ['Koordinator Influencer und PR', 'Erster Marathon']],
}

const impactCopy = {
  ro: { title: 'Impactul Asociației Blondie', subtitle: 'Rezultatele misiunii Blondie în ultimii 7 ani.', link: 'Află mai multe despre Blondie' },
  en: { title: 'The impact of Asociația Blondie', subtitle: 'The results of Blondie’s mission over the past 7 years.', link: 'Learn more about Blondie' },
  de: { title: 'Die Wirkung von Asociația Blondie', subtitle: 'Die Ergebnisse der Blondie-Mission in den letzten 7 Jahren.', link: 'Mehr über Blondie erfahren' },
}

function ExternalLink({ children, href, className = '' }) { return <a className={className} href={href} target="_blank" rel="noreferrer">{children}</a> }

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [language, setLanguage] = useState('ro')
  const t = copy[language]
  const closeMenu = () => setMenuOpen(false)
  const corporateEmail = `mailto:${socialLinks.email}?subject=${encodeURIComponent('Propunere parteneriat Fight for Flights')}`
  const sectionIds = ['cauza', 'echipa', 'proiectul', 'sponsori']

  return <main>
    <nav className="nav shell" aria-label="Main navigation"><a className="wordmark" href="#acasa" onClick={closeMenu} aria-label="Fight for Flights, acasă"><img src="/assets/logo.png" alt="Fight for Flights" /></a><button className="menu-button" type="button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open menu">{menuOpen ? <X size={22} /> : <Menu size={22} />}</button><div className={`nav-links ${menuOpen ? 'is-open' : ''}`}>{t.nav.map((label, index) => <a href={`#${sectionIds[index]}`} onClick={closeMenu} key={label}>{label}</a>)}<ExternalLink className="nav-blondie" href={socialLinks.blondie}>{t.blondie} <ArrowUpRight size={15} /></ExternalLink><label className="language-control"><Globe2 size={14} /><span className="sr-only">Language</span><select className="language-select" value={language} onChange={(event) => setLanguage(event.target.value)} aria-label="Select language"><option value="ro">RO</option><option value="en">EN</option><option value="de">DE</option></select></label><ExternalLink className="button button-small" href={socialLinks.galantom}>{t.donate} <ArrowUpRight size={15} /></ExternalLink></div></nav>

    <section className="hero shell" id="acasa"><div className="hero-copy reveal"><p className="eyebrow"><span className="eyebrow-line" /> {t.date}</p><h1>{t.title}</h1><p className="hero-lede">{t.mission}</p><div className="hero-actions"><ExternalLink className="button button-primary" href={socialLinks.galantom}>{t.donateGalantom} <ArrowUpRight size={18} /></ExternalLink><a className="text-link" href="#proiectul">{t.discover} <span>↘</span></a></div></div><div className="hero-side reveal reveal-delay"><div className="hero-mark"><Plane size={38} strokeWidth={1.5} /><span>{t.run}</span></div><div className="progress-panel"><div className="progress-heading"><span>{t.progress}</span><strong>{progress.percentage.toFixed(0)}%</strong></div><div className="progress-track" aria-label={`${t.progress} ${progress.percentage.toFixed(0)}%`}>{progress.individualWidth > 0 && <span className="progress-individual" style={{ width: `${progress.individualWidth}%` }} />}{progress.corporateWidth > 0 && <span className="progress-corporate" style={{ width: `${progress.corporateWidth}%` }} />}</div><div className="progress-total"><strong>{formatEur(progress.totalEur)}</strong><span>{t.from} {formatEur(campaignStats.targetEur)}</span></div><div className="progress-legend"><span><i className="dot dot-individual" /> {t.individual}</span><span><i className="dot dot-corporate" /> {t.sponsors}</span></div></div></div></section>

    <section className="impact-band"><div className="shell impact-wrap"><div className="impact-heading"><span className="impact-label">Blondie</span><h2>{impactCopy[language].title}</h2><p>{impactCopy[language].subtitle}</p></div><div className="impact-grid"><div><span className="impact-number">350+</span><span>{t.impact[0]}</span></div><div><span className="impact-number">1.300+</span><span>{t.impact[1]}</span></div><div><span className="impact-number">40.000 €</span><span>{t.impact[2]}</span></div></div><ExternalLink className="impact-link" href={socialLinks.blondie}>{impactCopy[language].link} <ArrowUpRight size={15} /></ExternalLink></div></section>
    <section className="section shell cause-section" id="cauza"><div className="section-kicker">{t.causeKicker}</div><div className="cause-grid"><div><h2>{t.causeTitle}</h2></div><div className="cause-copy"><p>{t.causeP1}</p><p>{t.causeP2}</p><ExternalLink className="text-link" href={socialLinks.blondie}>{t.learn} <ArrowUpRight size={17} /></ExternalLink></div></div></section>
    <section className="section shell team-section" id="echipa"><div className="section-kicker">{t.teamKicker}</div><div className="section-intro"><h2>{t.teamTitle}</h2><p>{t.teamIntro}</p></div><div className="team-grid">{teamMembers.map((member, index) => <article className="team-card" key={member.id}><div className={`portrait portrait-${index + 1}`}>{member.photoUrl ? <img src={member.photoUrl} alt={member.name} /> : <span>{member.name.split(' ').map((part) => part[0]).join('')}</span>}</div><div className="team-meta"><div><h3>{member.name}</h3><span className={`flag flag-${member.locationCode}`} title={member.locationLabel} aria-label={member.locationLabel} /></div><p>{memberCopy[language][index][0]}</p><small>{memberCopy[language][index][1]}</small></div></article>)}</div></section>
    <section className="project-section" id="proiectul"><div className="shell project-grid"><div><div className="section-kicker">{t.projectKicker}</div><h2>{t.projectTitle}</h2></div><div className="project-copy"><p>{t.projectText}</p><div className="project-pill"><Trophy size={20} /><span>{t.goal}<br /><strong>40.000 €</strong></span></div></div></div></section>
    <section className="section shell sponsors-section" id="sponsori"><div className="section-kicker">{t.partnershipKicker}</div><div className="sponsor-grid"><div><h2>{t.partnershipTitle}</h2><p>{t.partnershipText}</p><a className="button button-primary" href={corporateEmail}>{t.becomePartner} <Mail size={17} /></a></div><div className="sponsor-empty"><span className="empty-plus">+</span><p>{t.firstPartners}</p><a className="text-link" href={corporateEmail}>{t.discuss} <ArrowUpRight size={16} /></a></div></div></section>
    <footer className="footer"><div className="shell footer-grid"><div className="wordmark footer-mark"><img src="/assets/logo.png" alt="Fight for Flights" /></div><p>{t.footer}</p><div className="footer-links"><ExternalLink href={socialLinks.instagram}><ArrowUpRight size={17} /> Instagram</ExternalLink><ExternalLink href={socialLinks.galantom}><ArrowUpRight size={17} /> Galantom</ExternalLink><a href={`mailto:${socialLinks.email}`}><Mail size={17} /> Email</a></div></div><div className="shell footer-bottom"><span>© 2026 Fight for Flights</span><span>{t.disclaimer}</span></div></footer>
  </main>
}

export default App
